{
  "type": "record",
  "name": "AddressAvro",
  "namespace": "io.github.torvehammok.avro.common",
  "fields": [
    {
      "name": "line1",
      "type": [
        "null",
        "string"
      ],
      "avro.java.string": "String",
      "default": null
    },
    {
      "name": "line2",
      "type": [
        "null",
        "string"
      ],
      "avro.java.string": "String",
      "default": null
    },
    {
      "name": "city",
      "type": [
        "null",
        "string"
      ],
      "avro.java.string": "String",
      "default": null
    },
    {
      "name": "state",
      "type": [
        "null",
        "string"
      ],
      "avro.java.string": "String",
      "default": null
    },
    {
      "name": "postalCode",
      "type": [
        "null",
        "string"
      ],
      "avro.java.string": "String",
      "default": null
    },
    {
      "name": "country",
      "type": [
        "null",
        "string"
      ],
      "avro.java.string": "String",
      "default": null
    }
  ]
}
