{
  "type": "record",
  "name": "CustomerUpdateAvro",
  "namespace": "io.github.torvehammok.ordoeventi.avro",
  "fields": [
    {
      "name": "customerId",
      "type": [
        "null",
        "string"
      ],
      "avro.java.string": "String",
      "default": null
    },
    {
      "name": "name",
      "type": [
        "null",
        "string"
      ],
      "avro.java.string": "String",
      "default": null
    },
    {
      "name": "email",
      "type": [
        "null",
        "string"
      ],
      "avro.java.string": "String",
      "default": null
    },
    {
      "name": "phoneNumber",
      "type": [
        "null",
        "string"
      ],
      "avro.java.string": "String",
      "default": null
    },
    {
      "name": "status",
      "type": [
        "null",
        "io.github.torvehammok.ordoeventi.avro.CustomerStatusAvro"
      ],
      "default": null
    },
    {
      "name": "balance",
      "type": [
        "null",
        "io.github.torvehammok.avro.common.MoneyAvro"
      ],
      "default": null
    },
    {
      "name": "address",
      "type": [
        "null",
        "io.github.torvehammok.avro.common.AddressAvro"
      ],
      "default": null
    }
  ]
}
